include $(TOPDIR)/rules.mk

LUCI_TITLE:=ChirpStack REST API
LUCI_DEPENDS:=+luci-base
PKG_MAINTAINER:=Orne Brocaar <info@brocaar.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
