include $(TOPDIR)/rules.mk

LUCI_TITLE:=ChirpStack Concentratord (RAK7268v2)
LUCI_DEPENDS:=+luci-base +luci-app-chirpstack-concentratord
PKG_MAINTAINER:=Orne Brocaar <info@brocaar.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
