include $(TOPDIR)/rules.mk

LUCI_TITLE:=ChirpStack UDP Forwarder (slot1)
LUCI_DEPENDS:=+luci-base +luci-app-chirpstack-udp-forwarder
PKG_MAINTAINER:=Orne Brocaar <info@brocaar.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
