include $(TOPDIR)/rules.mk

LUCI_TITLE:=ChirpStack MQTT Forwarder (slot2)
LUCI_DEPENDS:=+luci-base +luci-app-chirpstack-mqtt-forwarder
PKG_MAINTAINER:=Orne Brocaar <info@brocaar.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
